---
- name: Create the ddclient configuration folder
  ansible.builtin.file:
    path: "{{ __ddclient_configuration_directory }}"
    state: directory
    owner: "{{ ddclient_owner }}"
    group: "{{ ddclient_group }}"
    mode: 0750

- name: Create configuration file
  ansible.builtin.template:
    src: "{{ ddclient_configuration_template }}"
    dest: "{{ __ddclient_configuration_location }}"
    owner: "{{ ddclient_owner }}"
    group: "{{ ddclient_group }}"
    backup: "{{ ddclient_backup }}"
    mode: 0600

- name: Create the cache directory
  ansible.builtin.file:
    path: "{{ __ddclient_cache_directory }}"
    state: directory
    owner: "{{ ddclient_owner }}"
    group: "{{ ddclient_group }}"
    mode: '0750'

- name: Create the systemd file
  ansible.builtin.template:
    src: "{{ ddclient_service_template }}"
    dest: "{{ __ddclient_service_file }}"
    owner: "{{ ddclient_owner }}"
    group: "{{ ddclient_group }}"
    mode: 0644
  when: ansible_os_family != 'FreeBSD' and not ddclient_install_from_source
  notify:
    - Disable_Service_DDClient
    - Enable_Service_DDClient

- name: List some items
  ansible.builtin.debug:
    msg:
    - "__ddclient_configuration_directory: {{ __ddclient_configuration_directory }}"
    - "__ddclient_configuration_location:  {{ __ddclient_configuration_location }}"
    - "__ddclient_cache_director:          {{ __ddclient_cache_directory }}"
  tags: debug
