- name: Install ddclient.
  community.general.pkgng:
    name: ddclient
    state: present

- ansible.builtin.set_fact:
    ddclient_owner: "root" 
    ddclient_group: "wheel" 
    __ddclient_configuration_directory: /usr/local/etc/
    __ddclient_configuration_directory_mode: 0755
