---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  become: true
  tasks:

    - name: populate service facts
      ansible.builtin.service_facts:

    - name: Check service is running
      ansible.builtin.assert:
        that:
          - ansible_facts.services["ddclient.service"] is defined
          - ansible_facts.services["ddclient.service"].state == 'running'
          - ansible_facts.services["ddclient.service"].status is match('enabled.*')
          - ansible_facts.services["ddclient.service"].source == 'systemd'

    - name: Retrieve configuration
      ansible.builtin.stat:
        path: /etc/ddclient/ddclient.conf
      register: conf

    - name: Check that configuration exists
      ansible.builtin.assert:
        that:
          - conf.stat.exists
          - conf.stat.mode == '0600'
          - conf.stat.isreg
          - conf.stat.pw_name == 'root'
          - conf.stat.gr_name == 'root'
          - conf.stat.readable
